# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: flow/legacy/entities/account.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("flow/legacy/entities/account.proto", :syntax => :proto3) do
    add_message "entities.Account" do
      optional :address, :bytes, 1
      optional :balance, :uint64, 2
      optional :code, :bytes, 3
      repeated :keys, :message, 4, "entities.AccountKey"
    end
    add_message "entities.AccountKey" do
      optional :index, :uint32, 1
      optional :public_key, :bytes, 2
      optional :sign_algo, :uint32, 3
      optional :hash_algo, :uint32, 4
      optional :weight, :uint32, 5
      optional :sequence_number, :uint32, 6
    end
  end
end

module Entities
  Account = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("entities.Account").msgclass
  AccountKey = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("entities.AccountKey").msgclass
end
