# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: flow/legacy/entities/block.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'
require 'flow/legacy/entities/collection_pb'
require 'flow/legacy/entities/block_seal_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("flow/legacy/entities/block.proto", :syntax => :proto3) do
    add_message "entities.Block" do
      optional :id, :bytes, 1
      optional :parent_id, :bytes, 2
      optional :height, :uint64, 3
      optional :timestamp, :message, 4, "google.protobuf.Timestamp"
      repeated :collection_guarantees, :message, 5, "entities.CollectionGuarantee"
      repeated :block_seals, :message, 6, "entities.BlockSeal"
      repeated :signatures, :bytes, 7
    end
  end
end

module Entities
  Block = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("entities.Block").msgclass
end
