# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: flow/legacy/entities/block_seal.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("flow/legacy/entities/block_seal.proto", :syntax => :proto3) do
    add_message "entities.BlockSeal" do
      optional :block_id, :bytes, 1
      optional :execution_receipt_id, :bytes, 2
      repeated :execution_receipt_signatures, :bytes, 3
      repeated :result_approval_signatures, :bytes, 4
    end
  end
end

module Entities
  BlockSeal = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("entities.BlockSeal").msgclass
end
