# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: flow/legacy/entities/transaction.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("flow/legacy/entities/transaction.proto", :syntax => :proto3) do
    add_message "entities.Transaction" do
      optional :script, :bytes, 1
      repeated :arguments, :bytes, 2
      optional :reference_block_id, :bytes, 3
      optional :gas_limit, :uint64, 4
      optional :proposal_key, :message, 5, "entities.Transaction.ProposalKey"
      optional :payer, :bytes, 6
      repeated :authorizers, :bytes, 7
      repeated :payload_signatures, :message, 8, "entities.Transaction.Signature"
      repeated :envelope_signatures, :message, 9, "entities.Transaction.Signature"
    end
    add_message "entities.Transaction.ProposalKey" do
      optional :address, :bytes, 1
      optional :key_id, :uint32, 2
      optional :sequence_number, :uint64, 3
    end
    add_message "entities.Transaction.Signature" do
      optional :address, :bytes, 1
      optional :key_id, :uint32, 2
      optional :signature, :bytes, 3
    end
    add_enum "entities.TransactionStatus" do
      value :UNKNOWN, 0
      value :PENDING, 1
      value :FINALIZED, 2
      value :EXECUTED, 3
      value :SEALED, 4
      value :EXPIRED, 5
    end
  end
end

module Entities
  Transaction = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("entities.Transaction").msgclass
  Transaction::ProposalKey = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("entities.Transaction.ProposalKey").msgclass
  Transaction::Signature = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("entities.Transaction.Signature").msgclass
  TransactionStatus = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("entities.TransactionStatus").enummodule
end
