# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: flow/execution/execution.proto

require 'google/protobuf'

require 'flow/entities/account_pb'
require 'flow/entities/event_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("flow/execution/execution.proto", :syntax => :proto3) do
    add_message "flow.execution.PingRequest" do
    end
    add_message "flow.execution.PingResponse" do
    end
    add_message "flow.execution.GetAccountAtBlockIDRequest" do
      optional :block_id, :bytes, 1
      optional :address, :bytes, 2
    end
    add_message "flow.execution.GetAccountAtBlockIDResponse" do
      optional :account, :message, 1, "flow.entities.Account"
    end
    add_message "flow.execution.ExecuteScriptAtBlockIDRequest" do
      optional :block_id, :bytes, 1
      optional :script, :bytes, 2
      repeated :arguments, :bytes, 3
    end
    add_message "flow.execution.ExecuteScriptAtBlockIDResponse" do
      optional :value, :bytes, 1
    end
    add_message "flow.execution.GetEventsForBlockIDsResponse" do
      repeated :results, :message, 1, "flow.execution.GetEventsForBlockIDsResponse.Result"
    end
    add_message "flow.execution.GetEventsForBlockIDsResponse.Result" do
      optional :block_id, :bytes, 1
      optional :block_height, :uint64, 2
      repeated :events, :message, 3, "flow.entities.Event"
    end
    add_message "flow.execution.GetEventsForBlockIDsRequest" do
      optional :type, :string, 1
      repeated :block_ids, :bytes, 2
    end
    add_message "flow.execution.GetTransactionResultRequest" do
      optional :block_id, :bytes, 1
      optional :transaction_id, :bytes, 2
    end
    add_message "flow.execution.GetTransactionResultResponse" do
      optional :status_code, :uint32, 1
      optional :error_message, :string, 2
      repeated :events, :message, 3, "flow.entities.Event"
    end
  end
end

module Execution
  PingRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("flow.execution.PingRequest").msgclass
  PingResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("flow.execution.PingResponse").msgclass
  GetAccountAtBlockIDRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("flow.execution.GetAccountAtBlockIDRequest").msgclass
  GetAccountAtBlockIDResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("flow.execution.GetAccountAtBlockIDResponse").msgclass
  ExecuteScriptAtBlockIDRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("flow.execution.ExecuteScriptAtBlockIDRequest").msgclass
  ExecuteScriptAtBlockIDResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("flow.execution.ExecuteScriptAtBlockIDResponse").msgclass
  GetEventsForBlockIDsResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("flow.execution.GetEventsForBlockIDsResponse").msgclass
  GetEventsForBlockIDsResponse::Result = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("flow.execution.GetEventsForBlockIDsResponse.Result").msgclass
  GetEventsForBlockIDsRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("flow.execution.GetEventsForBlockIDsRequest").msgclass
  GetTransactionResultRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("flow.execution.GetTransactionResultRequest").msgclass
  GetTransactionResultResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("flow.execution.GetTransactionResultResponse").msgclass
end
