# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: flow/entities/account.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("flow/entities/account.proto", :syntax => :proto3) do
    add_message "flow.entities.Account" do
      optional :address, :bytes, 1
      optional :balance, :uint64, 2
      optional :code, :bytes, 3
      repeated :keys, :message, 4, "flow.entities.AccountKey"
      map :contracts, :string, :bytes, 5
    end
    add_message "flow.entities.AccountKey" do
      optional :index, :uint32, 1
      optional :public_key, :bytes, 2
      optional :sign_algo, :uint32, 3
      optional :hash_algo, :uint32, 4
      optional :weight, :uint32, 5
      optional :sequence_number, :uint32, 6
      optional :revoked, :bool, 7
    end
  end
end

module Entities
  Account = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("flow.entities.Account").msgclass
  AccountKey = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("flow.entities.AccountKey").msgclass
end
