# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: flow/entities/block_header.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("flow/entities/block_header.proto", :syntax => :proto3) do
    add_message "flow.entities.BlockHeader" do
      optional :id, :bytes, 1
      optional :parent_id, :bytes, 2
      optional :height, :uint64, 3
      optional :timestamp, :message, 4, "google.protobuf.Timestamp"
    end
  end
end

module Entities
  BlockHeader = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("flow.entities.BlockHeader").msgclass
end
