# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: flow/entities/collection.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("flow/entities/collection.proto", :syntax => :proto3) do
    add_message "flow.entities.Collection" do
      optional :id, :bytes, 1
      repeated :transaction_ids, :bytes, 2
    end
    add_message "flow.entities.CollectionGuarantee" do
      optional :collection_id, :bytes, 1
      repeated :signatures, :bytes, 2
    end
  end
end


module Entities
  Collection = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("flow.entities.Collection").msgclass
  CollectionGuarantee = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("flow.entities.CollectionGuarantee").msgclass
end
