# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: flow/legacy/access/access.proto

require 'google/protobuf'

require 'flow/legacy/entities/account_pb'
require 'flow/legacy/entities/block_header_pb'
require 'flow/legacy/entities/block_pb'
require 'flow/legacy/entities/collection_pb'
require 'flow/legacy/entities/event_pb'
require 'flow/legacy/entities/transaction_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("flow/legacy/access/access.proto", :syntax => :proto3) do
    add_message "access.PingRequest" do
    end
    add_message "access.PingResponse" do
    end
    add_message "access.GetLatestBlockHeaderRequest" do
      optional :is_sealed, :bool, 1
    end
    add_message "access.GetBlockHeaderByIDRequest" do
      optional :id, :bytes, 1
    end
    add_message "access.GetBlockHeaderByHeightRequest" do
      optional :height, :uint64, 1
    end
    add_message "access.BlockHeaderResponse" do
      optional :block, :message, 1, "entities.BlockHeader"
    end
    add_message "access.GetLatestBlockRequest" do
      optional :is_sealed, :bool, 1
    end
    add_message "access.GetBlockByIDRequest" do
      optional :id, :bytes, 1
    end
    add_message "access.GetBlockByHeightRequest" do
      optional :height, :uint64, 1
    end
    add_message "access.BlockResponse" do
      optional :block, :message, 1, "entities.Block"
    end
    add_message "access.GetCollectionByIDRequest" do
      optional :id, :bytes, 1
    end
    add_message "access.CollectionResponse" do
      optional :collection, :message, 1, "entities.Collection"
    end
    add_message "access.SendTransactionRequest" do
      optional :transaction, :message, 1, "entities.Transaction"
    end
    add_message "access.SendTransactionResponse" do
      optional :id, :bytes, 1
    end
    add_message "access.GetTransactionRequest" do
      optional :id, :bytes, 1
    end
    add_message "access.TransactionResponse" do
      optional :transaction, :message, 1, "entities.Transaction"
    end
    add_message "access.TransactionResultResponse" do
      optional :status, :enum, 1, "entities.TransactionStatus"
      optional :status_code, :uint32, 2
      optional :error_message, :string, 3
      repeated :events, :message, 4, "entities.Event"
    end
    add_message "access.GetAccountRequest" do
      optional :address, :bytes, 1
    end
    add_message "access.GetAccountResponse" do
      optional :account, :message, 1, "entities.Account"
    end
    add_message "access.GetAccountAtLatestBlockRequest" do
      optional :address, :bytes, 1
    end
    add_message "access.AccountResponse" do
      optional :account, :message, 1, "entities.Account"
    end
    add_message "access.GetAccountAtBlockHeightRequest" do
      optional :address, :bytes, 1
      optional :block_height, :uint64, 2
    end
    add_message "access.ExecuteScriptAtLatestBlockRequest" do
      optional :script, :bytes, 1
      repeated :arguments, :bytes, 2
    end
    add_message "access.ExecuteScriptAtBlockIDRequest" do
      optional :block_id, :bytes, 1
      optional :script, :bytes, 2
      repeated :arguments, :bytes, 3
    end
    add_message "access.ExecuteScriptAtBlockHeightRequest" do
      optional :block_height, :uint64, 1
      optional :script, :bytes, 2
      repeated :arguments, :bytes, 3
    end
    add_message "access.ExecuteScriptResponse" do
      optional :value, :bytes, 1
    end
    add_message "access.GetEventsForHeightRangeRequest" do
      optional :type, :string, 1
      optional :start_height, :uint64, 2
      optional :end_height, :uint64, 3
    end
    add_message "access.GetEventsForBlockIDsRequest" do
      optional :type, :string, 1
      repeated :block_ids, :bytes, 2
    end
    add_message "access.EventsResponse" do
      repeated :results, :message, 1, "access.EventsResponse.Result"
    end
    add_message "access.EventsResponse.Result" do
      optional :block_id, :bytes, 1
      optional :block_height, :uint64, 2
      repeated :events, :message, 3, "entities.Event"
    end
    add_message "access.GetNetworkParametersRequest" do
    end
    add_message "access.GetNetworkParametersResponse" do
      optional :chain_id, :string, 1
    end
  end
end

module Access
  PingRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("access.PingRequest").msgclass
  PingResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("access.PingResponse").msgclass
  GetLatestBlockHeaderRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("access.GetLatestBlockHeaderRequest").msgclass
  GetBlockHeaderByIDRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("access.GetBlockHeaderByIDRequest").msgclass
  GetBlockHeaderByHeightRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("access.GetBlockHeaderByHeightRequest").msgclass
  BlockHeaderResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("access.BlockHeaderResponse").msgclass
  GetLatestBlockRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("access.GetLatestBlockRequest").msgclass
  GetBlockByIDRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("access.GetBlockByIDRequest").msgclass
  GetBlockByHeightRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("access.GetBlockByHeightRequest").msgclass
  BlockResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("access.BlockResponse").msgclass
  GetCollectionByIDRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("access.GetCollectionByIDRequest").msgclass
  CollectionResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("access.CollectionResponse").msgclass
  SendTransactionRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("access.SendTransactionRequest").msgclass
  SendTransactionResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("access.SendTransactionResponse").msgclass
  GetTransactionRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("access.GetTransactionRequest").msgclass
  TransactionResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("access.TransactionResponse").msgclass
  TransactionResultResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("access.TransactionResultResponse").msgclass
  GetAccountRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("access.GetAccountRequest").msgclass
  GetAccountResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("access.GetAccountResponse").msgclass
  GetAccountAtLatestBlockRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("access.GetAccountAtLatestBlockRequest").msgclass
  AccountResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("access.AccountResponse").msgclass
  GetAccountAtBlockHeightRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("access.GetAccountAtBlockHeightRequest").msgclass
  ExecuteScriptAtLatestBlockRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("access.ExecuteScriptAtLatestBlockRequest").msgclass
  ExecuteScriptAtBlockIDRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("access.ExecuteScriptAtBlockIDRequest").msgclass
  ExecuteScriptAtBlockHeightRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("access.ExecuteScriptAtBlockHeightRequest").msgclass
  ExecuteScriptResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("access.ExecuteScriptResponse").msgclass
  GetEventsForHeightRangeRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("access.GetEventsForHeightRangeRequest").msgclass
  GetEventsForBlockIDsRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("access.GetEventsForBlockIDsRequest").msgclass
  EventsResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("access.EventsResponse").msgclass
  EventsResponse::Result = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("access.EventsResponse.Result").msgclass
  GetNetworkParametersRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("access.GetNetworkParametersRequest").msgclass
  GetNetworkParametersResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("access.GetNetworkParametersResponse").msgclass
end
