# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: flow/legacy/execution/execution.proto for package 'execution'

require 'grpc'
require 'flow/legacy/execution/execution_pb'

module Execution
  module ExecutionAPI
    # ExecutionAPI is the API provided by the execution nodes.
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'execution.ExecutionAPI'

      # Ping is used to check if the access node is alive and healthy.
      rpc :Ping, ::Execution::PingRequest, ::Execution::PingResponse
      # Accounts
      #
      # GetAccountAtBlockID gets an account by address at the given block ID
      rpc :GetAccountAtBlockID, ::Execution::GetAccountAtBlockIDRequest, ::Execution::GetAccountAtBlockIDResponse
      # Scripts
      #
      # ExecuteScriptAtBlockID executes a ready-only Cadence script against the
      # execution state at the block with the given ID.
      rpc :ExecuteScriptAtBlockID, ::Execution::ExecuteScriptAtBlockIDRequest, ::Execution::ExecuteScriptAtBlockIDResponse
      # Events
      #
      # GetEventsForBlockIDs retrieves events for all the specified block IDs that
      # have the given type
      rpc :GetEventsForBlockIDs, ::Execution::GetEventsForBlockIDsRequest, ::Execution::GetEventsForBlockIDsResponse
      # Transaction
      #
      # GetTransactionResult gets the result of a transaction.
      rpc :GetTransactionResult, ::Execution::GetTransactionResultRequest, ::Execution::GetTransactionResultResponse
    end

    Stub = Service.rpc_stub_class
  end
end
